name: CI

on:
  pull_request:
    branches:
    - master
    - main
  push:
    branches:
    - master
    - main

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit build
        pip install .
    - name: Build package
      run: python -m build
    - name: Run pre-commit
      run: pre-commit run --all-files
